import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Link from 'next/link';
import { useContext, useEffect, useState } from 'react';
import axios from 'axios';
import { GetGamesContext } from '../context/GetGamesContext';

interface getGames {
	id: string;
	homeTeam: string;
	awayTeam: string;
	startTime: string;
	teamOneOdds: {
		name: string;
		odds: number;
	};
	teamTwoOdds: {
		name: string;
		odds: number;
	};
}

type GamesContext = {
	upcomingGames: getGames[];
};

export default function Home() {
	const { upcomingGames } = useContext(GetGamesContext) as GamesContext;

	return (
		<div className={styles.container}>
			<Head>
				<title>Betting Odds</title>
				<meta name='description' content='Generated by create next app' />
			</Head>

			<main className={styles.mainContainer}>
				<div className={styles.navigationContainer}>
					<button className={styles.navigation}>UpComing Games</button>
					<button className={styles.navigation}>Finished Games</button>
				</div>
				<div className={styles.upcomingGamesContainer}>
					{upcomingGames.map((game, index) => (
						<Link
							className={styles.displayGameGridContainer}
							key={index}
							href={`/placebet/${game.id}`}
							// href={{ pathname: '/placebet', query: { id: game.id } }}
						>
							<div className={`${styles.date} ${styles.gridColSpanFive}`}>
								{game.startTime}
							</div>
							<p className={styles.winnerSentence}>Winner (Incl. Overtime)</p>
							<div className={`${styles.team} ${styles.alignTeamAndOdds}`}>
								<p className={styles.fontSize}>{game.homeTeam}</p>
								<p className={styles.fontSize}>{game.teamOneOdds.odds}</p>
							</div>
							<p className={styles.versus}>vs</p>

							<div className={`${styles.teamTwo} ${styles.alignTeamAndOdds}`}>
								<p className={styles.fontSize}>{game.awayTeam}</p>
								<p className={styles.fontSize}>{game.teamTwoOdds.odds}</p>
							</div>
						</Link>
					))}
				</div>
			</main>
		</div>
	);
}
