import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Link from 'next/link';
import { useContext, useEffect, useState } from 'react';
import { GetGamesContext } from '../context/GetGamesContext';

interface getGames {
	id: string;
	homeTeam: string;
	awayTeam: string;
	startTime: string;
	teamOneOdds: {
		odds: number;
	};
	teamTwoOdds: {
		odds: number;
	};
}

type GamesContext = {
	upcomingGames: getGames[];
};

export default function Home() {
	const { upcomingGames } = useContext(GetGamesContext) as GamesContext;

	const [games, setGames] = useState(true);

	return (
		<div className={styles.container}>
			<Head>
				<title>BetScore Home</title>
				<meta name='description' content='Generated by create next app' />
			</Head>

			<main className={styles.mainContainer}>
				<div className={styles.introduction}>
					<span className={styles.introHeader}>
						Basketball Betting Simplified
					</span>
					<p className={styles.introHook}>
						Your ultimate destination to bet on upcoming NBA games. Get the best
						odds and make big profits from the games you bet on!
					</p>
				</div>
				<div className={styles.gamesContainer}>
					<div className={styles.layover}>
						<div className={styles.navigationContainer}>
							<div
								className={`${styles.navigation} `}
								onClick={() => setGames(true)}
							>
								Games
							</div>
							<div
								className={`${styles.navigation} `}
								onClick={() => setGames(false)}
							>
								Completed
							</div>
							<span
								className={`${styles.underline} ${
									!games ? styles.active : styles.notActive
								}`}
							/>
						</div>
					</div>
					{games ? (
						upcomingGames.map((game, index) => (
							<div className={styles.displayGameGridContainer} key={index}>
								<span
									className={`${styles.date} ${
										game.startTime === 'Live' && styles.live
									}`}
								>
									{game.startTime}
								</span>
								<span className={styles.winnerSentence}>
									Winner (Incl. Overtime)
								</span>
								<hr className={`${styles.thinLine} ${styles.thinLineMiddle}`} />
								<hr className={`${styles.thinLine} ${styles.thinLineEnd}`} />
								<div className={styles.teams}>
									<span className={` ${styles.fontSize}`}>{game.homeTeam}</span>
									<span className={styles.dash}>-</span>
									<span className={`${styles.fontSize}`}>{game.awayTeam}</span>
								</div>
								<div className={styles.buttonContainer}>
									<Link
										className={styles.button}
										href={{ pathname: '/placebet', query: { id: game.id } }}
									>
										<div className={styles.test}>
											<span className={styles.fontSize}>{game.homeTeam}</span>
										</div>
										<span>{game.teamOneOdds.odds}</span>
									</Link>
									<Link
										className={styles.button}
										href={{ pathname: '/placebet', query: { id: game.id } }}
									>
										<div className={styles.test}>
											<span className={styles.fontSize}>{game.awayTeam}</span>
										</div>
										<span>{game.teamTwoOdds.odds}</span>
									</Link>
								</div>
							</div>
						))
					) : (
						<div>Finished Games</div>
					)}
				</div>
			</main>
		</div>
	);
}
