import Head from 'next/head';
import styles from '../styles/homePage/Home.module.css';
import { useEffect, useState } from 'react';
import UpcomingGames from '../components/homePage/UpcomingGames';
import CompletedGames from '../components/homePage/CompletedGames';
import News from '../components/homePage/News';
import axios from 'axios';
import LiveGames from '../components/homePage/LiveGames';

interface CompletedGame {
	id: string;
	homeTeam: string;
	awayTeam: string;
	homeTeamScore: {
		score: string;
	};
	awayTeamScore: {
		score: string;
	};
	date: string;
}
interface LiveGame {
	homeTeam: string;
	awayTeam: string;
	homeTeamScore: number;
	awayTeamScore: number;
}

export default function Home() {
	const [games, setGames] = useState(true);

	const [completedGames, setCompletedGames] = useState<CompletedGame[]>([]);
	const [liveGames, setLiveGames] = useState<LiveGame[]>([]);
	const [tabs, setTabs] = useState({
		bet: true,
		news: true,
		liveScore: true,
	});

	useEffect(() => {
		if (window.innerWidth < 1283) {
			setTabs({ bet: true, news: false, liveScore: false });
		}

		function reportWindowSize() {
			if (window.innerWidth < 1283) {
				setTabs({ bet: true, news: false, liveScore: false });
			} else {
				setTabs({ bet: true, news: true, liveScore: true });
			}
		}
		window.addEventListener('resize', reportWindowSize);
		//  Cleanup for componentWillUnmount
		return () => window.removeEventListener('resize', reportWindowSize);
	}, []);

	useEffect(() => {
		let completedGames: CompletedGame[] = [];
		let liveGames: LiveGame[] = [];

		const options = {
			method: 'GET',
			url: 'https://odds.p.rapidapi.com/v4/sports/basketball_nba/scores',
			params: { daysFrom: '2', dateFormat: 'unix' },
			headers: {
				'X-RapidAPI-Key': '2cbb011960msh3ff72f4f58249a1p127b8bjsnc63ffc1d70d9',
				'X-RapidAPI-Host': 'odds.p.rapidapi.com',
			},
		};

		axios.request(options).then(response => {
			response.data.forEach((data: any) => {
				if (data.completed === false) {
					if (data.scores === null) {
						return;
					} else {
						liveGames.push({
							homeTeam: data.home_team,
							awayTeam: data.away_team,
							homeTeamScore: data.scores[0].score,
							awayTeamScore: data.scores[1].score,
						});
						return;
					}
				}

				const milliseconds = data.commence_time * 1000;
				const timeStamp = new Date(milliseconds);
				const date = timeStamp.toLocaleDateString('en-US', {
					weekday: 'long',
					month: 'long',
					day: 'numeric',
					hour: 'numeric',
					minute: 'numeric',
				});

				completedGames.push({
					id: data.id,
					homeTeam: data.home_team,
					awayTeam: data.away_team,
					homeTeamScore: {
						score: data.scores[0].score || '0',
					},
					awayTeamScore: {
						score: data?.scores[1].score || '0',
					},
					date: date,
				});
			});
			setCompletedGames(completedGames);
			setLiveGames(liveGames);
		});
	}, []);

	return (
		<div className={styles.container}>
			<Head>
				<title>BetScore Home</title>
				<meta name='description' content='Generated by create next app' />
			</Head>

			<main className={styles.mainContainer}>
				{tabs.liveScore && (
					<div className={styles.liveGames}>
						<LiveGames liveGames={liveGames} />
					</div>
				)}
				<div className={styles.introduction}>
					<span className={styles.introHeader}>
						Basketball Betting Simplified
					</span>
					<p className={styles.introHook}>
						Your ultimate destination to bet on upcoming NBA games. Get the best
						odds and make big profits from the games you bet on!
					</p>
				</div>
				<div className={styles.tabs}>
					<button
						onClick={() =>
							setTabs({ bet: true, news: false, liveScore: false })
						}
					>
						Bet
					</button>
					<button
						onClick={() =>
							setTabs({ bet: false, news: true, liveScore: false })
						}
					>
						News
					</button>
					<button
						onClick={() =>
							setTabs({ bet: false, news: false, liveScore: true })
						}
					>
						Live Score
					</button>
				</div>
				<div className={styles.newsAndGamesContainer}>
					{tabs.bet && (
						<div className={styles.gamesContainer}>
							<div className={styles.layover}>
								<div className={styles.navigationContainer}>
									<div
										className={`${styles.navigation} `}
										onClick={() => setGames(true)}
									>
										Games
									</div>
									<div
										className={`${styles.navigation} `}
										onClick={() => setGames(false)}
									>
										Completed
									</div>
									<span
										className={`${styles.underline} ${
											!games ? styles.active : styles.notActive
										}`}
									/>
								</div>
							</div>

							{games === true ? (
								<UpcomingGames />
							) : (
								<CompletedGames completedGames={completedGames} />
							)}
						</div>
					)}
					{tabs.news && <News />}
				</div>
			</main>
		</div>
	);
}
